name: moviesapp
description: "Futurama Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  mobx: ^2.6.0
  mobx_codegen: ^2.7.0
  shared_preferences: ^2.5.3

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
